---
title: "A Heatmap of ELA Results for Grade 8 Black Students"
author: "Kecen<br>[kp3056@tc.columbia.edu](mailto: kp3056@tc.columbia.edu)"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Replication
Below is the replication of the [2022 NYC Equity Indicators Report](https://academiccommons.columbia.edu/doi/10.7916/a143-aq05).

```{r}

library(openxlsx)
library(tidyverse)

if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("ComplexHeatmap")

library(ComplexHeatmap) 

```

```{r}

# sheet 4: "Ethnicity"
dat = read.xlsx("https://infohub.nyced.org/docs/default-source/default-document-library/district-ela-results-2013-2019-(public).xlsx",sheet=4)

```

```{r}

head(dat)
summary(dat)

```

```{r}

# generate frequency tables for variables Category, Grade, and Year
table(dat$Category)
table(dat$Grade)
table(dat$Year)

```

```{r}

# retain observations without "s"
ela <- dat %>%
  filter(Mean.Scale.Score != "s") %>%   # suppressed cells are removed
  mutate(mean_scale_score = as.numeric(Mean.Scale.Score)) # change data type from character to numeric

```

```{r}

# select years (2013-2017), grade (8), and category (Black)
ela1 <- ela %>%
  filter(Year == 2013 | Year == 2014 | Year == 2015 | Year == 2016 | Year == 2017, Grade == 8, Category == "Black") %>%  
  select(mean_scale_score, District, Year) %>%
  pivot_wider(names_from = Year, values_from = mean_scale_score) # reorganize the data from long to wide 

```

```{r}

# not including District numbers in the calculation
ht_dat1 <- ela1 %>% select(-District) %>% as.data.frame()

# add district numbers
rownames(ht_dat1) <- ela1$District

```

```{r}

# create heatmap1
Heatmap(as.matrix(ht_dat1), # convert the data frame to a matrix
        heatmap_legend_param = list(title = "Grade 8 ELA: Black Students Heatmap",
                                    title_gp = gpar(fontfamily = "Times"),
        labels_gp = gpar(fontfamily = "Times")), # heatmap name
        rect_gp = gpar(col = "white", lwd = 1), # separate the cells by white lines
        cluster_columns = FALSE,   #  cluster rows only;  the default distance metric - “euclidean”, and the default agglomeration (clustering) method - “complete”
        row_names_gp = gpar(fontfamily = "Times"),
        column_names_gp = gpar(fontfamily = "Times"))

```

## A little extension
After a few changes to the details of the heatmap above, the heatmap below features a clearer layout and muted colors.

```{r}

library(RColorBrewer)
library(circlize)

my_col <- colorRamp2(c(min(ht_dat1), median(as.matrix(ht_dat1)), max(ht_dat1)), brewer.pal(3, "Spectral")) # choose color palette

# create heatmap1
hm <- Heatmap(as.matrix(ht_dat1), # convert the data frame to a matrix
        col = my_col, # set color
        heatmap_legend_param = list(
        title = "mean scale score",
        title_gp = gpar(fontfamily = "Times", fontsize=12),
        labels_gp = gpar(fontfamily = "Times", fontsize=10)), # heatmap legend name
        rect_gp = gpar(col = "white", lwd = 1), # separate the cells by white lines
        cluster_columns = FALSE,   #  cluster rows only;  the default distance metric - “euclidean”, and the default agglomeration (clustering) method - “complete”
        row_names_gp = gpar(fontfamily = "Times"),
        column_names_gp = gpar(fontfamily = "Times"),
        column_names_rot = 0, # display column name horizontally
        column_names_centered = TRUE # center align column name and column
        )

# create heatmap title
draw(hm,
   column_title="Grade 8 ELA: Black Students Heatmap",
   column_title_gp=grid::gpar(fontfamily = "Times", fontsize=16, fontface = "bold")
   )


```
